### ISSUE TITLE
setTitle doesn't work

### ISSUE THREAD

**Issue by akulihin** [StartAutomating/ScriptDeck#106]
I want to change the title of the hardware button and tried the following in the ps1 script I was running with "PowerShell Script" command:
`Send-StreamDeck -Context $event.MessageData.Context -Title "Sharks"`
and
```
$Payload = [Ordered]@{ 
title = "Sharks"
target = "both"
state  = 0
}
Send-StreamDeck -Context $event.MessageData.Context -EventName "setTitle" -Payload $Payload   
```

Both options don't do anything, they are not throwing an error, but they also do not change the title

**Comment by StartAutomating** [comment]
@mylorik you're likely running into the "joy" that is setTitle's behavior when a static title has been set.

If you've changed the title in the UI, setTitle will always be ignored.

This is barely documented and an easy place to trip up.

If this is not what's going on, let me know.

**Comment by akulihin** [comment]
That was the issue, thank you.
