### ISSUE TITLE
PowerShell Version

### ISSUE THREAD

**Issue by AlexHedley** [StartAutomating/ScriptDeck#120]
Hi, thanks for making this.

Is there a way to set which version of **PowerShell** it uses?

`$PSVersionTable`

```bash
Name                           Value                                                                                         
----                           -----                                                                                         
PSVersion                      5.1.19041.5247                                                                                
```

Can I make it use **7** instead?

```bash
Name                           Value
----                           -----
PSVersion                      7.4.6
```

**Comment by StartAutomating** [comment]
There are two plugins, one for PowerShell Core (ScriptDeck), and one for Windows PowerShell ( WindowsScriptDeck ).

So just use the PowerShell Core version and you should be good to go.

Hope this helps!

**Comment by AlexHedley** [comment]
Great, thanks, I’ll give that a try :)

**ScriptDeck**
https://marketplace.elgato.com/product/scriptdeck-927e59aa-b42d-4da7-84cc-8c78f4dd7e18

**Windows ScriptDeck**
https://marketplace.elgato.com/product/windows-scriptdeck-857f01dd-8fd4-44d5-8ec7-67ac850b21d3
