### ISSUE TITLE
Start-Process Multiaction Error

### ISSUE THREAD

**Issue by NathanielLowson** [StartAutomating/ScriptDeck#47]
I have three Start-Process actions that are used to run different python programs, the only variables being input are the path to the scripts. Two of the scripts are supposed to be used in Multiactions as part of a 'Start' and 'End' stream button. When using normally they work perfectly, when using inside the multiaction I receive 'A parameter cannot be found that matches parameter name 'Length' in the powershell error log. Below are the powershell error logs. Really enjoying the solution otherwise. 

![image](https://user-images.githubusercontent.com/54043660/203908215-dfd7a52a-c39d-427e-a81c-a955bb063a67.png)
![image](https://user-images.githubusercontent.com/54043660/203908410-c62059f9-710f-45af-95da-1c5eef3fbdf9.png)

**Comment by StartAutomating** [comment]
@NathanielLowson Thanks for the issue!

Is there any way you could share the event handlers you have set up in the multiaction?

I'm not quite sure what would be causing this, and would love your help in figuring out how to reproduce the issue.

**Comment by NathanielLowson** [comment]
Here's a screenshot of the multiaction, it just sets the scene for the stream, starts the stream and then runs the python script, the first two events fire fine and then when the Start-Process runs the powershell error above shows. The Start-Process runs perfectly fine outside of the multiaction and this is happening with a similar multiaction that runs a different python script. Let me know if there's anything else you need from my end, happy to help. 
![image](https://user-images.githubusercontent.com/54043660/204113083-277a88ba-ce8f-48bc-9e37-24a1c2cbb9ac.png)

**Comment by StartAutomating** [comment]
@NathanielLowson

There should be logs in the StreamDeckPlugin directory.

```PowerShell
Install-Module ScriptDeck -Force -Scope CurrentUser
Import-Module ScriptDeck
Get-StreamDeckPlugin -Name ScriptDeck |
    Select-Object -ExpandProperty PluginPath |
    Split-Path |
    Get-ChildItem -Filter *.log
```

We're looking for the settings that are passed to the script, as well as any additional error info that might be there.

**Comment by NathanielLowson** [comment]
Below are the logs I got after running one of the multifunctions. 

StreamDeck Logs
00:08:21.336                     StreamDeck                        ESDActionsGridViewModel::onKeyPressed():        Key 23 pressed: com.elgato.streamdeck.multiactions.routine
00:08:21.522                     StreamDeck                        ESDActionsGridViewModel::onKeyReleased():       Key 23 released: com.elgato.streamdeck.multiactions.routine
00:09:05.295                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_da235e0f73cad73e58f66afea9c7deaf>::()::<lambda_edf3f60a824e4535b7414c8c0c192809>::operator ()(): Restarting plugin 'ScriptDeck' after one minute
00:09:05.321                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_da235e0f73cad73e58f66afea9c7deaf>::operator ()(): The plugin 'ScriptDeck' exited normally with code 1
00:09:05.321                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_da235e0f73cad73e58f66afea9c7deaf>::operator ()(): Restarting plugin 'ScriptDeck'

ScriptDeck Logs
KeyDown Pressed @ 11/27/2022 00:08:21
{"action":"com.start-automating.windowsscriptdeck.start-process","context":"49D9F48A6FAF0148EA712BCFA9775246","device":"776DF677537A0E6932ABA5DA1F08809C","event":"keyUp","payload":{"isInMultiAction":true,"settings":{"FilePath":"F:\\Documents\\Content\\Programs\\endStream.pyw","Length":2,"LongLength":2,"Rank":1,"WillAppear":"","WillDisappear":""},"userDesiredState":0}}


VS Here are the logs I got from running one of the actions normally

StreamDeck Log
00:12:00.574                     StreamDeck                        ESDActionsGridViewModel::onKeyPressed():        Key 30 pressed: com.start-automating.windowsscriptdeck.start-process
00:12:00.607                     StreamDeck                        KA_Custom::HandleCommandFromPlugin():           Unknown messageType 'showOK': {"context":"3939BBCD74767C29D3E2D14109B878BE","event":"showOK"}
00:12:00.698                     StreamDeck                        ESDActionsGridViewModel::onKeyReleased():       Key 30 released: com.start-automating.windowsscriptdeck.start-process
00:12:05.462                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_da235e0f73cad73e58f66afea9c7deaf>::()::<lambda_edf3f60a824e4535b7414c8c0c192809>::operator ()(): Restarting plugin 'ScriptDeck' after one minute
00:12:05.493                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_da235e0f73cad73e58f66afea9c7deaf>::operator ()(): The plugin 'ScriptDeck' exited normally with code 1

ScriptDeck Log
KeyDown Pressed @ 11/27/2022 00:12:00
{"action":"com.start-automating.windowsscriptdeck.start-process","context":"3939BBCD74767C29D3E2D14109B878BE","device":"776DF677537A0E6932ABA5DA1F08809C","event":"keyUp","payload":{"coordinates":{"column":6,"row":3},"isInMultiAction":false,"settings":{"FilePath":"F:\\Documents\\Content\\Programs\\endStream.pyw","WillAppear":"","WillDisappear":""}}}

**Comment by StartAutomating** [comment]
Thanks for that!

This was really helped, and revealed a pair of things:

1. My guess wasn't that far off.  It looks like there's a .Length property set when it's in a multiaction, which in turn got seen as a potential parameter.

The old code to check for this was:

~~~PowerShell
if($command.parameters.($prop.Name)) {
    $settingsSplat[$prop.Name] = $prop.Value
}
~~~


The new code is:

~~~PowerShell
if ($command.parameters[$prop.Name]) {
    $settingsSplat[$prop.Name] = $prop.Value
}
~~~

In the first code, .Length would pass the check, because a dictionary would have a length property (but not a "length" key).

In the second code, .Length should fail the check.

You should be able to download the bits from the branch if you'd like to test this before release later today.

Thanks!
